language: objective-c
osx_image: xcode7.2
script:
  - xcodebuild -scheme "GCM Sender" -workspace "GCM Sender.xcworkspace" clean build test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
