osx_image: xcode7
language: objective-c
before_install:
    - gem install cocoapods
script:
    - xcodebuild clean build test -workspace "GCM Sender.xcworkspace" -scheme "GCM Sender" ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
